redis:
      host: 172.20.69.42
      port: 6379
      password:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
      timeout: 0
spring:
     activemq:
       broker-url: tcp://localhost:61616

management:
      port: 8081
      context-path: /manage
      security:
        enabled: false